export const assets ={
    santafe:"./imgsantafe/puente-colgante.jpg",
    0:"./imgsantafe/0.png" ,
    1:"./imgsantafe/1.png" ,
    2:"./imgsantafe/2.png" ,
    3:"./imgsantafe/3.png" ,
    4:"./imgsantafe/4.png",
    5:"./imgsantafe/5.png" ,
    6:"./imgsantafe/6.png",
    7:"./imgsantafe/7.png",
    8:"./imgsantafe/8.png",
    9:"./imgsantafe/9.png",
    10:"./imgsantafe/10.png",
    11:"./imgsantafe/11.png",
    12:"./imgsantafe/12.png",
    13:"./imgsantafe/13.png",
    14:"./imgsantafe/14.png",
    15:"./imgsantafe/15.png",
    16:"./imgsantafe/16.png",
    17:"./imgsantafe/17.png",
    18:"./imgsantafe/18.png",
    19:"./imgsantafe/19.png",
    santa:"./imgsantafe/santafe.jpg",
    botonok:"./imgsantafe/boton-ok.png",
    back:"./imgsantafe/back.jpg"
}

